name: dinov2
channels:
  - defaults
  - pytorch
  - xformers
  - conda-forge
  - nvidia/label/cuda-11.7.0
dependencies:
  - python=3.10
  - pytorch::pytorch=1.13.1
  - pytorch::pytorch-cuda=11.7.0
  - pytorch::torchvision
  - omegaconf
  - torchmetrics
  - fvcore
  - iopath
  - xformers::xformers=0.0.18
  - pip
  - pip:
    - git+https://github.com/facebookincubator/submitit
    - --extra-index-url https://pypi.nvidia.com
    - cuml-cu11