# Practical semi-supervised training configuration for DINOv2
# This configuration shows a realistic setup for semi-supervised training

MODEL:
  WEIGHTS: ""

# Semi-supervised training with HuggingFace dataset
data:
  dataset: "cifar10" # Replace with your dataset
  config_name: null
  train_split: "train"
  val_split: "test"
  img_col_name: "img"
  label_col_names: ["label"]
  cache_dir: null
  data_dir: null
  trust_remote_code: true
  streaming: false
  num_workers: 4

  # Semi-supervised configuration
  semisupervised:
    main_label_col: "label"
    supervised_proportion: 0.05 # Use only 5% of data as supervised
    seed: 813846

# Training configuration
train:
  batch_size_per_gpu: 32
  output_dir: "outputs/semisup_cifar10"
  num_workers: 4
  OFFICIAL_EPOCH_LENGTH: 1250

  # Enable semi-supervised training
  use_semisupervised: true
  supervised_per_batch: 3 # 3 supervised samples per batch of 32

# Smaller model for faster training
student:
  arch: vit_small
  patch_size: 16
  drop_path_rate: 0.1
  ffn_layer: mlp
  block_chunks: 0
  init_values: 1.0
  qkv_bias: true
  proj_bias: true
  ffn_bias: true

teacher:
  momentum_teacher: 0.996
  final_momentum_teacher: 1.0
  warmup_teacher_temp: 0.04
  teacher_temp: 0.04
  warmup_teacher_temp_epochs: 0

# Reduced training setup for experimentation
optim:
  epochs: 50 # Reduced for faster experimentation
  weight_decay: 0.04
  weight_decay_end: 0.4
  base_lr: 0.0005
  lr: 0.0005
  warmup_epochs: 5
  min_lr: 1.0e-06
  clip_grad: 3.0
  freeze_last_layer: 1
  scaling_rule: sqrt_wrt_1024
  patch_embed_lr_mult: 0.2
  layerwise_decay: 1.0
  adamw_beta1: 0.9
  adamw_beta2: 0.999

# Smaller crops for CIFAR-10
crops:
  global_crops_scale: [0.4, 1.0]
  local_crops_scale: [0.05, 0.4]
  local_crops_number: 8
  global_crops_size: 224
  local_crops_size: 96

# Loss configuration
dino:
  loss_weight: 1.0
  head_n_prototypes: 8192 # Smaller for CIFAR-10
  head_bottleneck_dim: 256
  head_hidden_dim: 2048
  head_nlayers: 3

ibot:
  loss_weight: 1.0
  mask_ratio_min_max: [0.1, 0.5]
  mask_sample_probability: 0.5
  separate_head: false
  head_n_prototypes: 8192
  head_bottleneck_dim: 256
  head_hidden_dim: 2048
  head_nlayers: 3

# Evaluation settings
evaluation:
  eval_period_iterations: 1250 # Evaluate every epoch

# Precision settings
compute_precision:
  grad_scaler: true
  teacher:
    backbone:
      sharding_strategy: NO_SHARD
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    dino_head:
      sharding_strategy: NO_SHARD
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    ibot_head:
      sharding_strategy: NO_SHARD
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
  student:
    backbone:
      sharding_strategy: NO_SHARD
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    dino_head:
      sharding_strategy: NO_SHARD
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    ibot_head:
      sharding_strategy: NO_SHARD
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
