student:
  arch: vit_giant2
  patch_size: 14
  ffn_layer: swiglufused
  num_register_tokens: 4
  interpolate_antialias: true
  interpolate_offset: 0.0
crops:
  global_crops_size: 518  # this is to set up the position embeddings properly
  local_crops_size: 98